spring.application.name=web-services
#logging.level.org.springframework=

#spring.security.user.name=maysara
#spring.security.user.password=maysara

jwt.signing.key.secret=mySecret
jwt.get.token.uri=/authenticate
jwt.refresh.token.uri=/refresh
jwt.http.request.header=Authorization
jwt.token.expiration.in.seconds=604800

spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:test
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.data.jpa.repositories.bootstrap-mode=default
spring.datasource.username=maysara
spring.datasource.password=maysara